### PR TITLE
Roaring bitmaps

### LINKED ISSUE #32: rdbms-sink branch: cancel SQL query when HTTP client disconnects.
Currently the SQL transaction continues processing after the HTTP client has cancelled its request. It will eventually fail like this:

```
10:37:39.659 [Grizzly-worker(3)] INFO  c.conveyal.osmlib.PostgresOSMSource - Begin node iteration
Exception in thread "Thread-2" java.lang.RuntimeException: java.io.IOException: Broken pipe
        at com.conveyal.osmlib.PBFOutput.writeOneBlob(PBFOutput.java:116)
        at com.conveyal.osmlib.PBFOutput.run(PBFOutput.java:308)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Broken pipe
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:51)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
        at org.glassfish.grizzly.nio.transport.TCPNIOUtils.flushByteBuffer(TCPNIOUtils.java:149)
        at org.glassfish.grizzly.nio.transport.TCPNIOUtils.writeCompositeBuffer(TCPNIOUtils.java:87)
        at org.glassfish.grizzly.nio.transport.TCPNIOAsyncQueueWriter.write0(TCPNIOAsyncQueueWriter.java:112)
        at org.glassfish.grizzly.nio.transport.TCPNIOAsyncQueueWriter.write0(TCPNIOAsyncQueueWriter.java:91)
        at org.glassfish.grizzly.nio.AbstractNIOAsyncQueueWriter.write(AbstractNIOAsyncQueueWriter.java:261)
        at org.glassfish.grizzly.nio.AbstractNIOAsyncQueueWriter.write(AbstractNIOAsyncQueueWriter.java:170)
        at org.glassfish.grizzly.nio.AbstractNIOAsyncQueueWriter.write(AbstractNIOAsyncQueueWriter.java:70)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransportFilter.handleWrite(TCPNIOTransportFilter.java:126)
        at org.glassfish.grizzly.filterchain.TransportFilter.handleWrite(TransportFilter.java:191)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$8.execute(ExecutorResolver.java:111)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
        at org.glassfish.grizzly.filterchain.FilterChainContext.write(FilterChainContext.java:848)
        at org.glassfish.grizzly.filterchain.FilterChainContext.write(FilterChainContext.java:817)
        at org.glassfish.grizzly.http.io.OutputBuffer.flushBuffer(OutputBuffer.java:1024)
        at org.glassfish.grizzly.http.io.OutputBuffer.write(OutputBuffer.java:680)
        at org.glassfish.grizzly.http.io.OutputBuffer.write(OutputBuffer.java:542)
        at org.glassfish.grizzly.http.server.NIOOutputStreamImpl.write(NIOOutputStreamImpl.java:75)
        at com.conveyal.osmlib.PBFOutput.writeOneBlob(PBFOutput.java:114)
        ... 2 more
```

### PR DESCRIPTION
**Pull request by mattwigway**
Fix #32 by using compressed bitmaps so we don't run out of memory when loading large OSM data.

### CODE REVIEW

File: src/main/java/com/conveyal/osmlib/NodeTracker.java [hunk 1]
```diff
@@ -1,84 +1,78 @@
...
  * Node numbers in OSM tend to be contiguous so maybe the blocks should be bigger.
- * Disabled debug statements have no measurable effect on speed (verified).
  *
  * MapDB TreeSets are much faster than MapDB HashSets, but in-memory NodeTrackers are
  * much faster than MapDB TreeSets.
+ *
+ * To save space, this uses RoaringBitmaps. RoaringBitmaps currently only support 32 bit keys
+ * so we use multiple RoaringBitmaps containing the low 32 bits, stored in a map from the high
+ * 32 bits to a roaringbitmap. Since the OSM IDs are concentrated towards the bottom of the long
+ * space (i.e. they only need, so far, one more than an int provides), only a few blocks are used.
```
Comment (abyrd) [inline src/main/java/com/conveyal/osmlib/NodeTracker.java]: I think this is intended to say "one more bit"

File: src/main/java/com/conveyal/osmlib/NodeTracker.java [hunk 2]
```diff
@@ -1,84 +1,78 @@
...
-    }
+    private Map<Integer, RoaringBitmap> blocks = new HashMap<>();
 
-    private int bit(long x) {
-        return (int)(x & LOW_MASK);
+    public void add(long x) {
+        int high = highIndex(x);
+        int low = lowIndex(x);
+
+        if (!blocks.containsKey(high)) {
```
Comment (abyrd) [inline src/main/java/com/conveyal/osmlib/NodeTracker.java]: Typically rather than checking whether a map contains a key and then inserting, I would do the get() and then create and insert an empty element if the get() returns null. This way you only do one hash table look up in the case where the key is already present.

File: src/main/java/com/conveyal/osmlib/NodeTracker.java [hunk 3]
```diff
@@ -1,84 +1,78 @@
...
-        LOG.debug("get node {}: index {} bit {}", x, index(x), bit(x));
-        long[] block = block(x, false);
-        if (block == null) return false; 
-        return (block[index(x)] & (1L << bit(x))) != 0;
+    private static int highIndex (long key) {
+        return (int) (key >> 32);
+    }
+
+    private static int lowIndex (long key) {
+        return (int) key;
```
Comment (abyrd) [inline src/main/java/com/conveyal/osmlib/NodeTracker.java]: For all IDs with bit 31 set this is going to yield negative integers. https://docs.oracle.com/javase/specs/jls/se7/html/jls-5.html#jls-5.1.3 says "A narrowing conversion of a signed integer to an integral type T simply discards all but the n lowest order bits, where n is the number of bits used to represent type T. In addition to a possible loss of information about the magnitude of the numeric value, this may cause the sign of the resulting value to differ from the sign of the input value." Does the RoaringBitmap support storing negative integers?

File: src/main/java/com/conveyal/osmlib/OSM.java [hunk 4]
```diff
@@ -181,6 +181,7 @@ public void readFromFile(String filePath) {
                 // FIXME this takes two minutes on NL OSM. We should probably save the intersections in a MapDB table.
                 LOG.info("Detecting intersections...");
                 for (Way way : ways.values()) {
+                    if (way.hasTag("building")) continue;
```
Comment (abyrd) [inline src/main/java/com/conveyal/osmlib/OSM.java:184]: Oh, so you're only skipping the buildings on intersection detection. I was thinking we should skip them entirely when loading the PBF, that way we also save time and space saving building ways that we'll never use.

**Review by abyrd — CHANGES_REQUESTED** [review]

File: src/main/java/com/conveyal/osmlib/OSM.java (hunk 4 above)
Comment (mattwigway) [reply src/main/java/com/conveyal/osmlib/OSM.java:184]: Yes, that's not a bad idea but it makes the library less general-purpose; we could add a flag to do that as part of a separate pull request maybe.

File: src/main/java/com/conveyal/osmlib/NodeTracker.java (hunk 3 above)
Comment (mattwigway) [reply src/main/java/com/conveyal/osmlib/NodeTracker.java]: Yes, it just treats ints as unsigned, see https://github.com/RoaringBitmap/RoaringBitmap#unsigned-integers.

Comment (abyrd) [reply src/main/java/com/conveyal/osmlib/NodeTracker.java]: @mattwigway has found this: "Java lacks native unsigned integers, but integers are still considered to be unsigned within Roaring, and ordered according to  Integer.compareUnsigned. This means that Java will order the numbers like so 0, 1, ..., 2147483647, -2147483648, -2147483647,..., -1. To intepret correctly, you can use Integer.toUnsignedLong and Integer.toUnsignedString.” So this will work correctly.

File: src/main/java/com/conveyal/osmlib/OSM.java (hunk 4 above)
Comment (abyrd) [reply src/main/java/com/conveyal/osmlib/OSM.java:184]: This patch is only intended to fix intersection detection, so we've decided that skipping buildings entirely (if we ever do it) will be in another pull request.
